[WIP] 33 add user crud develop
SENG426-Summer-2022/vega-web-master pull request #41
Opened 2022-07-03 04:14 UTC by albie0019

# Changes
* Added new buttons beside each user column in the admin panel to manage them.
* Added a new page to manage users.
* Added four options (Delete user, Change First and Last name, Change Email, Add new user) to the new admin management page.
* Modified frontend server to include these new calls to the backend.

2022-07-03 04:51 UTC, ACHultman requested changes

2022-07-03 04:51 UTC, ACHultman commented on server/controller/AdminPanelController.js
> +router.get("/deleteuser", (req, res) => {
a DELETE or POST/PUT method may be more fitting for delete

2022-07-03 04:51 UTC, ACHultman commented on server/controller/AdminPanelController.js
> +router.get("/changeemail", (req, res) => {
maybe a POST (`router.post`) for this and `/changeusername`?

2022-07-03 04:51 UTC, ACHultman commented on server/controller/AdminPanelController.js
> +	const {newemail} = req.query;
```suggestion
	const {username, newemail} = req.query;
```

2022-07-03 04:51 UTC, ACHultman commented on server/controller/AdminPanelController.js
> +	const {newUserLastname} = req.query;
```suggestion
	const {username, newUserFirstname, newUserLastname} = req.query;
```

2022-07-03 04:51 UTC, ACHultman commented on server/services/AdminPanelAPI.js
> +	console.log(url);
these console logs may be too much (and the ones in the other functions here)

2022-07-03 04:51 UTC, ACHultman commented on src/components/pages/AdminUserManagement.js
> +import {Form, Table, Button} from "react-bootstrap";
nitpick: unused imports, remove pls

2022-07-03 04:51 UTC, ACHultman commented on src/components/pages/AdminUserManagement.js
> +        console.log(user.jwt)
probably shouldn't console log this stuff (same for the other functions in this file)

2022-07-03 04:51 UTC, ACHultman commented on src/components/pages/AdminUserManagement.js
> +        var newUserFirstname = prompt("enter new Firstname")
`var` is okay but it is good practice to use `let` or `const`, `const` in this case (not changing)

2022-07-03 04:51 UTC, ACHultman commented on src/components/pages/AdminUserManagement.js
> +            </div>
maybe we should have this Add button on the list page, makes more sense. and maybe green (`success` in bootstrap)

2022-07-03 04:51 UTC, ACHultman commented on src/components/pages/AdminUserManagement.js
> +            <div className={"section1"}>
we could also include the user's (first and last) names. and maybe put those in the header and have the username/email in the body below so the admin can easily see what their current one is

2022-07-03 04:51 UTC, ACHultman commented on src/components/pages/AdminUserManagement.js
> +        var newUserLastname = prompt("enter new Lastname")
ideally we should get the new values (names, email) in a form on the page instead of a browser prompt

2022-07-03 04:51 UTC, ACHultman commented on src/components/pages/AdminUserManagement.js
> +                alert(res)
this (and the other one) alerts an object
![image](https://user-images.githubusercontent.com/38937780/177025215-7fe71147-9d6c-4637-b469-b3992794d851.png)

2022-07-03 05:00 UTC, albie0019 commented on server/controller/AdminPanelController.js
> +router.get("/deleteuser", (req, res) => {
I'll have to look into how this change affects/modifies the backend. If doable, I'll fix this in a future commit

2022-07-03 05:01 UTC, albie0019 commented on server/controller/AdminPanelController.js
> +router.get("/changeemail", (req, res) => {
Same response as the above comment

2022-07-03 05:03 UTC, albie0019 commented on server/services/AdminPanelAPI.js
> +	console.log(url);
Agreed. They were stowaways from the earlier master branch

2022-07-03 05:08 UTC, ACHultman commented on server/controller/AdminPanelController.js
> +router.get("/deleteuser", (req, res) => {
unrelated to this PR, but looks like `enableuser` and `changerole` should also be POST or PUT on the spring backend (`RequestMethod.POST`)

2022-07-03 05:12 UTC, albie0019 commented on src/components/pages/AdminUserManagement.js
> +import {Form, Table, Button} from "react-bootstrap";
Cool

2022-07-03 05:12 UTC, albie0019 commented on src/components/pages/AdminUserManagement.js
> +        console.log(user.jwt)
Yup. Will remove

2022-07-03 05:12 UTC, albie0019 commented on src/components/pages/AdminUserManagement.js
> +        var newUserFirstname = prompt("enter new Firstname")
Will change to `const`

2022-07-03 05:14 UTC, albie0019 commented on src/components/pages/AdminUserManagement.js
> +        var newUserLastname = prompt("enter new Lastname")
Yeah, a prompt isn't the right way to read info. I just did that because of time crunch.

2022-07-03 05:15 UTC, albie0019 commented on src/components/pages/AdminUserManagement.js
> +                alert(res)
This is an active bug that I'm trying to fix. For deletion, this one relayed the server's success response, so I thought I could do the same here.

2022-07-03 05:16 UTC, albie0019 commented on src/components/pages/AdminUserManagement.js
> +            <div className={"section1"}>
Makes sense

2022-07-03 05:17 UTC, albie0019 commented on src/components/pages/AdminUserManagement.js
> +            </div>
Did you mean the admin panel? I just added it here to conform to the user story we had written in the requirements doc in M1.

2022-07-03 05:20 UTC, albie0019 reviewed
Left some individual responses and some other quick corrections to code (removing console logs) as commits. More changes to come for the AdminUserManagement.js page as future commits.

2022-07-05 02:21 UTC, ACHultman approved these changes

2022-07-05 02:45 UTC, merged